name: violette_front
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0

  stacked: ^3.4.1
  stacked_services: ^1.5.0
  stacked_firebase_auth: ^2.21.0
  cloud_firestore: ^5.6.12
  table_calendar: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  stacked_generator: ^1.5.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  

  assets:
    - assets/images/
