// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4WD1UafexxBqtcxZOweIMMzwI6D0S8gc',
    appId: '1:942876080772:web:93ba6709f42e04532ea0d1',
    messagingSenderId: '942876080772',
    projectId: 'violette-1f64e',
    authDomain: 'violette-1f64e.firebaseapp.com',
    storageBucket: 'violette-1f64e.firebasestorage.app',
    measurementId: 'G-KRMGYQM434',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQlzS9aHX9T1w13moGgfE3P7rSTQNs3BA',
    appId: '1:942876080772:android:e9d0ae65120d390d2ea0d1',
    messagingSenderId: '942876080772',
    projectId: 'violette-1f64e',
    storageBucket: 'violette-1f64e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5NPzgBwtm2qgKC4gaPjWaQkjTUnqMhlQ',
    appId: '1:942876080772:ios:5aba8ac85d8397e02ea0d1',
    messagingSenderId: '942876080772',
    projectId: 'violette-1f64e',
    storageBucket: 'violette-1f64e.firebasestorage.app',
    iosBundleId: 'com.example.violetteFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5NPzgBwtm2qgKC4gaPjWaQkjTUnqMhlQ',
    appId: '1:942876080772:ios:5aba8ac85d8397e02ea0d1',
    messagingSenderId: '942876080772',
    projectId: 'violette-1f64e',
    storageBucket: 'violette-1f64e.firebasestorage.app',
    iosBundleId: 'com.example.violetteFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4WD1UafexxBqtcxZOweIMMzwI6D0S8gc',
    appId: '1:942876080772:web:868e9a1506d59ae32ea0d1',
    messagingSenderId: '942876080772',
    projectId: 'violette-1f64e',
    authDomain: 'violette-1f64e.firebaseapp.com',
    storageBucket: 'violette-1f64e.firebasestorage.app',
    measurementId: 'G-2SV183XCT0',
  );
}
